/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenyewaanpc;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

import static aplikasipenyewaanpc.Koneksi.koneksiDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class TransaksiSewa extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiSewa
     */
    public TransaksiSewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idTransaksi = new javax.swing.JTextField();
        jNama = new javax.swing.JTextField();
        jMerek = new javax.swing.JTextField();
        jLama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jHarga = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 30)); // NOI18N
        jLabel1.setText("TRANSAKSI PENYEWAAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel2.setText("ID Transaksi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel3.setText("Nama Penyewa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel4.setText("Merek/type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel5.setText("Lama Menyewa");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 191, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        jPanel1.add(idTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 127, 138, -1));
        jPanel1.add(jNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 127, 167, -1));
        jPanel1.add(jMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 127, 175, -1));
        jPanel1.add(jLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, -1));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel7.setText("Harga Sewa");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 91, -1, -1));
        jPanel1.add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 132, -1));
        jPanel1.add(jTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 167, -1));

        jButton1.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 121, 45));

        jButton2.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 108, 47));

        jButton3.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 111, 47));

        jButton4.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, 50));

        jButton5.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 110, 50));

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 850, 140));

        jButton6.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        jButton6.setText("Kembali");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 100, 40));

        jButton7.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton7.setText("Print");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void tampil_data(){
    DefaultTableModel tabel=new DefaultTableModel();
    tabel.addColumn("ID");
    tabel.addColumn("NAMA PENYEWA"); // untuk menampilkan title dibagian tabel dari data 
    tabel.addColumn("MEREK/TYPE");
    tabel.addColumn("HARGA SEWA");
    tabel.addColumn("LAMA SEWA");
    tabel.addColumn("TOTAL");
    
    try {
        java.sql.Connection conn=(java.sql.Connection)aplikasipenyewaanpc.Koneksi.koneksiDB();
        String sql = "select * from transaksisewa";  // koneksi database dan memilih tabel sesuai dengan nama tabel
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery(sql);
      while(rs.next())
        {
        tabel.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3), //untuk manampilkan hasil tambah data 
            rs.getString(4),
            rs.getString(5),
            rs.getString(6)});
        }
        jTable1.setModel(tabel);
        }
    catch (Exception e){
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int harga, lama, total;
        harga = Integer.parseInt(jHarga.getText());
        lama = Integer.parseInt(jLama.getText());  
        total = harga * lama;
        jTotal.setText((Integer.toString(total)));// untuk menghitung total harga sewa dengan berapa lama menyewa
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           new MenuPenyewaan().show();
           this.dispose();// kembali ke halaman menu
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String sql="insert into transaksisewa values('"
                    +idTransaksi.getText()+"','"
                    +jNama.getText()+"','"    //untuk menambahkan data ke mysql dan tabel 
                    +jMerek.getText()+"','"
                    +jHarga.getText()+"','"
                    +jLama.getText()+"','"
                    +jTotal.getText()+"')";
                 java.sql.Connection conn=(java.sql.Connection)aplikasipenyewaanpc.Koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql); //untuk koneksi ke mysql 
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil_data(); //memanggil kelas untuk menampilkan hasil tambah data
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
      idTransaksi.setText("");
      jNama.setText("");
      jMerek.setText(""); //ketika data berhasil ditambah akan otomatis  mengosong kan seluruh field
      jHarga.setText("");
      jLama.setText("");
      jTotal.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            try{
            String sql="update transaksisewa set nama= '" + jNama.getText()+
                    "', merek='" + jMerek.getText()+
                    "', harga='" + jHarga.getText()+   //koding untuk edit data di tabel dan di mysql
                    "', lama='" + jLama.getText()+
                    "', total='" + jTotal.getText()+
                    "' where id='" + idTransaksi.getText()+"'";
            java.sql.Connection conn=(java.sql.Connection)aplikasipenyewaanpc.Koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql); //untuk koneksi ke mysql
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil diedit");
            tampil_data(); //menampilkan kelas hasil edit data
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal edit");
            System.out.println(e.getMessage());
        } // TODO ad        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
    java.sql.Connection conn=(java.sql.Connection)aplikasipenyewaanpc.Koneksi.koneksiDB(); //koneksi ke mysql
    String sql = "delete from transaksisewa where id='"+idTransaksi.getText()+"' "; //memilih tabel sesuai id
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.executeUpdate(); JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
    tampil_data();   //koding untuk melakukan hapus data dan tampilkan hasil hapus data
    }
catch (Exception e){
JOptionPane.showMessageDialog(null,"Proses Penghapusan Gagal");
System.out.println(e.getMessage());
}             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         idTransaksi.setText("");
         jNama.setText("");
         jMerek.setText("");
         jHarga.setText("");
         jLama.setText("");
         jTotal.setText("");// mengosongkan field 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel tab = (DefaultTableModel)jTable1.getModel();
       idTransaksi.setText(tab.getValueAt(jTable1.getSelectedRow(), 0).toString());
       jNama.setText(tab.getValueAt(jTable1.getSelectedRow(), 1).toString());
       jMerek.setText(tab.getValueAt(jTable1.getSelectedRow(), 2).toString()); 
       jHarga.setText(tab.getValueAt(jTable1.getSelectedRow(),3).toString()); 
       jLama.setText(tab.getValueAt(jTable1.getSelectedRow(),4).toString());
       jTotal.setText(tab.getValueAt(jTable1.getSelectedRow(),5).toString());// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

       JasperReport report;
       String path = ".\\src\\aplikasipenyewaanpc\\TransaksiReport.jrxml";
      
       try{
        java.sql.Connection conn=(java.sql.Connection)aplikasipenyewaanpc.Koneksi.koneksiDB();
        report = (JasperReport)JRLoader.loadObjectFromFile(path);
        JasperPrint print = JasperFillManager.fillReport(path,null,conn);
        JasperViewer jv = new JasperViewer(print, false);
        jv.setVisible(true);
       
       } catch (SQLException | JRException ex) {
            Logger.getLogger(TransaksiSewa.class.getName()).log(Level.SEVERE, null, ex);
        }


// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiSewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLama;
    private javax.swing.JTextField jMerek;
    private javax.swing.JTextField jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTotal;
    // End of variables declaration//GEN-END:variables
}
